### PR TITLE
Refactored expose controller

### PR DESCRIPTION
**Pull request by jimmidyson**
Provides better separation of strategies & better error handling.

@rawlingsj Review would be good before we merge this if you can.

### CODE REVIEW

**Comment by jimmidyson** [comment]
Although the massive amount of dependency changes makes review pretty damn hard. Perhaps just pulling locally & trying it out would be the best idea?

**Comment by rawlingsj** [comment]
Sounds great! Yeah I'll pull the changes and give it a whirl.

**Comment by jimmidyson** [comment]
Yeah so it's the problem of changing from LoadBalancer type to NodePort type.

**Comment by jimmidyson** [comment]
Fixed in 32ad2a9

**Comment by rawlingsj** [comment]
tested nodeports on minishift, ingress on aws and routes on openshift dedicated

gofabric8 needs updating to use the new configmap format but I'll do that and ideally move it into the exposecontroller itself so it's self contained.

LGTM

**Comment by rawlingsj** [comment]
BTW thanks @jimmidyson for your time on this 👍

**Comment by jimmidyson** [comment]
Thanks for testing it out!

**Pull request merged**
