### PR TITLE
add ingress.class: gce ingress annotation by default #76

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@rawlingsj snapshot exposecontroller image is available for testing.  `docker pull docker.io/fabric8/exposecontroller:SNAPSHOT-PR-77-1`

**Comment by soarten** [comment]
Tested en working, even leaving the kube-lego path mapping in place! 

The question remains how this will impact those users relying on the current lego nginx default that might be overridden bij this annotation.

**Comment by rawlingsj** [comment]
Yeah - we may need to provide a flag to `gofabric8 deploy` which sets config in the exposecontroller configmap that tells us to add this annotation automatically.

**Comment by soarten** [comment]
`gofabric8 deploy` detects reasonable defaults depending on your environment, so it could to some extend infer this setting as well. 

I just did a clean installation and test with gofabric8 deploy and ran in some relates issues: 
- The exposecontroller annotation fix did not prevent it from overwriting the kube-lego ingress adaptation.
- The exposed services were created with type `ClusterIP` while `NodePort` is required when using the native GKE load balancer. I suppose thats an issues for another project.

**Comment by rawlingsj** [comment]
OK I understand this a bit more now.  We're just gearing up for a new major release so I'm not sure I'll have time to look at this until next week maybe.  I think until then to avoid confusion I'll close this PR until there's time to focus and test using Kube-lego with a GKE load balancer.

**Pull request closed without merging**
