### PR TITLE
use the same Makefile as gofabric8 so  we use a consistent approach t…

### PR DESCRIPTION
**Pull request by rawlingsj**
…hat also works with the shared golang release pipeline

### CODE REVIEW

**Comment by rawlingsj** [comment]
@jimmidyson when you get a few mins could you take a look at this.  We now use a shared library for golang pipelines rather than each one having their own approach.  

In doing so I've used the gofabric8 Makefile as a base to use with this and configmapcontroller.  

If using the gofabric8 Makefile sounds ok then I'll update the circle ci job as it's failing because `make cross` isn't there.  Alternatively I can add that back in and also update gofabric8 + exposecontroller to use the same.

**Comment by rawlingsj** [comment]
Alternatively I can just revert the Makefile changes and just add in the gh-release part.

**Comment by rawlingsj** [comment]
Actually @jimmidyson I think I'll just revert the Makefile changes as I guess its fair that each project is going to want to use different styles.

**Comment by jimmidyson** [comment]
Do you like talking to yourself?

**Comment by rawlingsj** [comment]
I get very bored listening to myself, no idea how you all put up with it!

**Pull request closed without merging**
