### PR TITLE
fixes #4 so we can ensure the exposeUrl is added to OAuthClients

### LINKED ISSUE #4: support adding the expose URL to OAuthClient
on OpenShift we need to put the externalUrl of a service into OAuthClients so that the OAuth redirect can go back to the service. e.g. logging in with the fabric8 console.

Right now we've some magic in gofabric8. It'd be nice to be able to run fabric8 on openshift with the minimum possible magic required (e.g. gofabric8). e.g. so that we can install fabric8 via the openshift console itself.

So it'd be nice when `exposecontroller` is running on OpenShift to also watch `OAuthClient` which have the same label (say `expose: true`?) then whenever the service gets annotated, we also check if there's an OAuthClient of the same name with that label, if so we ensure that the externalUrl is inside the list of redirects.

e.g. when using ingress, route or nodePort - its hard at install time to know what the serviceURL is gonna be when the `OAuthClient` gets created. So its cleaner for `exposecontroller` to add the serviceURL when it adds the `exposeUrl `annotation

### PR DESCRIPTION
**Pull request by jstrachan**

### CODE REVIEW

**Comment by jstrachan** [comment]
ok to test

**Comment by jstrachan** [comment]
[merge]

**Comment by jimmidyson** [comment]
Bit confused by this PR: you're adding all exposed urls to the oauthclient? Why?

**Comment by jstrachan** [comment]
an OAuthClient must contain the exposed URL, otherwise you can't login with OAuth to the external URL to a service.

We could only enable this logic of an OAuthClient is annotated with some magic annotation I guess - but when would you not want an external service URL to be in the OAuthClient redirectURLs?

**Comment by jimmidyson** [comment]
Why do you expect every external service to be authenticated with openshift oauth? I would expect that to be a tiny minority of external services. Openshift oauth is used to secure access to openshift resources, not to general applications which will have their own authentication requirements.

**Comment by jstrachan** [comment]
If a service wasn't authenticated with openshift OAuth then I'd not expect it to have an OAuthClient. 

Why would a Service have an OAuthClient if it didn't want to be authenticated by OpenShift OAuth?

**Comment by jimmidyson** [comment]
That's what I get for reviewing on my phone! Didn't notice the oauth client name check. Sorry for the noise!

**Comment by jstrachan** [comment]
no worries :) glad you're reviewing stuff though!

**Pull request merged**
